ARG BASE=docker.io/debian:stable-slim

FROM ghcr.io/initramfs-modules/initramfs:latest as initrd

FROM $BASE as builder
COPY --from=initrd /efi /efi

ENV REPO=/_tmp
COPY . $REPO/

RUN $REPO/containers/kernel.sh

FROM scratch
COPY --from=builder /boot /boot
COPY --from=builder /lib/modules /lib/modules
