FROM ghcr.io/initramfs-modules/kernel as kernel

FROM ghcr.io/initramfs-modules/boot as boot

FROM docker.io/alpine

#FROM ghcr.io/initramfs-modules/initramfs as initrd

COPY --from=kernel /boot /boot
COPY --from=kernel /lib/modules /lib/modules
#COPY --from=kernel /efi /efi
COPY --from=boot /efi /efi

ENV REPO=/_tmp
RUN find $REPO

RUN --mount=target=$REPO $REPO/containers/infra-build-kernel.sh

# output - /lib/modules /boot /efi
