ARG BASE=docker.io/ubuntu:jammy

FROM ghcr.io/gombos/kernel as k
FROM ghcr.io/gombos/rootfs as r
FROM ghcr.io/gombos/usrlocal as l

FROM $BASE
COPY --from=r /usr /rootfs
COPY --from=l /tmp /usrlocal
#COPY --from=k /tmp/kernel /tmp/kernel
ENV REPO=/_tmp

RUN --mount=target=$REPO $REPO/containers/infra-image.sh
