#ARG BASE=docker.io/debian:sid
ARG BASE=docker.io/0gombi0/homelab:minbase

FROM $BASE as builder

ENV REPO=/_tmp

RUN --mount=target=$REPO $REPO/bin/infra-build-root.sh base
RUN --mount=target=$REPO $REPO/bin/infra-build-root.sh extra

RUN mksquashfs / /tmp/squashfs.img -comp zstd
RUN ls -la /tmp/squashfs.img

FROM scratch
COPY --from=builder /tmp/squashfs.img /iso

