FROM ghcr.io/initramfs-modules/initramfs as initrd

FROM ghcr.io/initramfs-modules/kernel as kernel

FROM docker.io/alpine

ENV REPO=/_tmp

RUN --mount=target=$REPO $REPO/containers/packages.sh

COPY --from=initrd /efi /efi
COPY --from=kernel /boot /boot
COPY --from=kernel /lib/modules /lib/modules

RUN find /lib/modules/ boot/
