ARG BASE=ghcr.io/gombos/rootfs

FROM ghcr.io/gombos/rootfs as r

# compression takes 10 min
FROM alpine as pr
COPY --from=r / /rootfs
RUN apk add squashfs-tools && mksquashfs /rootfs /tmp/squashfs.img -comp zstd

FROM scratch
COPY --from=pr /tmp/squashfs.img /iso/squashfs.img

FROM ghcr.io/gombos/efi as efi
FROM ghcr.io/gombos/usrlocal as usrlocal

FROM $BASE as builder

COPY --from=pr /iso /iso
COPY --from=efi /efi /efi
COPY --from=usrlocal /iso /iso

ENV REPO=/_tmp
COPY . $REPO/
RUN --mount=target=$REPO $REPO/containers/infra-image.sh

FROM scratch
COPY --from=builder /tmp/linux.iso /tmp/linux.iso
