# Base image could be independent from rootfs

FROM ubuntu:jammy as base
#FROM ubuntu:kinetic as base

COPY bin/* /tmp/
COPY boot/ /tmp/
WORKDIR /tmp
#RUN ./infra-build-boot.sh

FROM scratch
#COPY --from=base /efi /efi
