#ARG BASE=docker.io/ubuntu:jammy

#FROM ghcr.io/gombos/efi as e
#FROM ghcr.io/gombos/package-rootfs as r
#FROM ghcr.io/gombos/usrlocal as l

#FROM $BASE as builder
#COPY --from=e /efi /efi
#COPY --from=e /boot /boot
#COPY --from=r /iso/squashfs.img /iso/squashfs.img
#COPY --from=l /iso/usrlocal.img /iso/usrlocal.img

ARG BASE=0gombi0/homelab-baremetal:extra

FROM ghcr.io/gombos/package-rootfs as pr
FROM ghcr.io/gombos/efi as efi
FROM ghcr.io/gombos/usrlocal as usrlocal

FROM $BASE as builder

COPY --from=pr /iso /iso
COPY --from=efi /efi /efi
COPY --from=usrlocal /iso /iso

ENV REPO=/_tmp
COPY . $REPO/
RUN --mount=target=$REPO $REPO/containers/infra-image.sh

FROM scratch
COPY --from=builder /tmp/linux.iso /tmp/linux.iso
