name: Container
on:
    workflow_dispatch:

permissions:
    packages: write
    contents: read

jobs:
    push_to_registry:
        name: container
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            max-parallel: 1
            matrix:
                config:
#                      - { tag: boot }
#                      - { tag: kernel    }
                      - { tag: efi }
#                      - { tag: rootfs    }
#                      - { tag: package-rootfs }
#                      - { tag: usrlocal    }
#                      - { tag: iso }

        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                  submodules: true

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2

            -   name: Login to GitHub Container Registry
                uses: docker/login-action@v2
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Set up env
                run: echo "repository_owner=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}

            -   name: Build and Push Container
                uses: docker/build-push-action@v3
                with:
                    context: .
                    file: containers/Dockerfile-${{ matrix.config.tag }}
                    tags: ghcr.io/${{env.repository_owner}}/${{ matrix.config.tag }}
                    push: true
