name: container
# runs for 10 min

on:
    workflow_dispatch:
        inputs:
            container:
                type: choice
                description: 'container'
                default: 'debian:sid'
                options:
                    - "ubuntu:24.04"   # devel
                    - "debian:sid"
                    - "debian:trixie"  # testing
                    - "ubuntu:mantic"  # rolling
            platform:
                type: choice
                description: 'platform'
                default: 'linux/arm64,linux/amd64'
                options:
                    - "linux/arm64,linux/amd64"
                    - "linux/amd64"
                    - "linux/arm64"

permissions:
    packages: write
    contents: read

jobs:
    container:
        runs-on: ubuntu-latest

        steps:
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v3
                with:
                    platforms: ${{ inputs.platform }}

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Login to GitHub Container Registry
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Set up env
                run: echo "repository_owner=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}

            -   name: container
                uses: docker/build-push-action@v5
                with:
                    push: true
                    file: containers/Dockerfile-container-${{ inputs.container }}
                    tags: ghcr.io/${{env.repository_owner}}/linux
                    platforms: ${{ inputs.platform }}
                    build-args: |
                        BUILDX_NO_DEFAULT_ATTESTATIONS: 1
