name: rootfs - base
# runs for 10 min

on:
    workflow_dispatch:

permissions:
    packages: write
    contents: read

jobs:
    rootfs:
        runs-on: ubuntu-latest

        steps:
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2

            -   name: Login to GitHub Container Registry
                uses: docker/login-action@v2
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Set up env
                run: echo "repository_owner=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}

            -   name: rootf
                uses: docker/build-push-action@v4
                with:
                    push: true
                    file: containers/Dockerfile-homelab
                    tags: ghcr.io/${{env.repository_owner}}/rootfs
